# Set prefix to C-a
set -g prefix C-a

unbind C-b

bind C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind Space last-window

bind \\ split-window -h
bind - split-window -v

set -g base-index 1
setw -g pane-base-index 1

unbind r 
bind r source-file ~/.tmux.conf

set-option -g default-shell /usr/bin/zsh
set -g mouse on
set-option -g status-position top
set -g automatic-rename on

# List of plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'xamut/tmux-weather'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)

set -g @catppuccin_date_time_text " %H:%M"
set -g @catppuccin_pane_default_text "#{b:pane_current_path}"
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_modules_left "directory"

run '~/.tmux/plugins/tpm/tpm'

set -g status-left ""
set -g status-right ""
set -agF status-right "#{E:@catppuccin_status_weather}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

run '~/.tmux/plugins/tpm/tpm'
