"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "#56B6C2"
  template = " {{ .Path }} "

    [blocks.segments.options]
    style = "folder"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:lavender"
  template = "{{ .HEAD }} "

    [blocks.segments.options]
    branch_icon = "\ue725 "
    cherry_pick_icon = "\ue29b "
    commit_icon = "\uf417 "
    fetch_status = false
    fetch_upstream_icon = false
    merge_icon = "\ue727 "
    no_commits_icon = "\uf0c3 "
    rebase_icon = "\ue728 "
    revert_icon = "\uf0e2 "
    tag_icon = "\uf412 "

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:closer"
  template = "\uf105"
