require('autocmds')
require('remap')
require('set')
require('plugins')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.colors')
require('plugins.gitsigns')
require('plugins.conform')
require('plugins.lsp')
require('plugins.lualines')

vim.opt.clipboard:append('unnamedplus')

require('vim._core.ui2').enable({})
